graph LR
classDef green fill:#9f6,stroke:#333;
classDef orange fill:#f96,stroke:#333;
classDef blue fill:#69f,stroke:#333;
classDef cyan fill:#aff,stroke:#333;
classDef fail fill:#f88,stroke:#333,text-decoration:line-through;

start((start)) -.-> A(("| (or)"))
A --> B("[a-z]")
A --> C(c)
A --> D(d)
B --> B1("[0-9]")
B1 --> B2("-")
B2 --> B3("[0-9]")
C --> C1(a)
C1 --> C2(t)
D --> D1(o)
D1 --> D2(g)
D2 --> END(<b><i>DONE</i></b>)
C2 --> END
B3 --> END
class A green;

subgraph step0: input char 'd'
W>pos1] -. create 3 threads .-> A
end

subgraph step1: char 'd' 
X>pos1] -. match and  move .-> B
Y>pos3] -. <b>fail</b>, drop thread .-> C
Z>pos2]  -. match and move .-> D
end

subgraph step2: char '2'
X1>pos1] -.match and move.-> B1
Y1>pos2] -.<b>fail</b>, drop thread.-> C1
end

subgraph step3: char '-'
X2>pos1] -.match and move.-> B2
end

class X,Z orange;
class W green;
class X1 blue
class X2,END cyan

