graph LR
classDef green fill:#9f6,stroke:#333;
classDef orange fill:#f96,stroke:#333;
classDef blue fill:#69f,stroke:#333;
classDef cyan fill:#aff,stroke:#333;

start((start)) -.-> A(("| (or)"))
A --> B("[a-z]")
A --> C(c)
A --> D(d)
B --> B1("[0-9]")
B1 --> B2("-")
B2 --> B3("[0-9]")
C --> C1(a)
C1 --> C2(t)
D --> D1(o)
D1 --> D2(g)
D2 --> END(DONE)
C2 --> END(DONE)
B3 --> END(DONE)
class A green;

subgraph step0
W>pos1] -.-> A
end

subgraph step1
X>pos1] -.-> B
Y>pos3] -.-> C
Z>pos2]  -.-> D
end

subgraph step2
X1>pos1] -.-> B1
Y1>pos3] -.-> C1
Z1>pos2]  -.-> D1

end

subgraph step3
X2>pos1] -.-> B2
end

class X,Y,Z orange;
class W green;
class X1 blue
class X2 cyan
